// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ouxrwfihdcdqmzfrtaij.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im91eHJ3ZmloZGNkcW16ZnJ0YWlqIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI0NTMxNDcsImV4cCI6MjA1ODAyOTE0N30.eWmjFUyRo_iILo3So8AMgbJoBzCsznGw4kSrvNIXFIs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);